version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - zip -r lambda-package.zip .

artifacts:
  files:
    - lambda-package.zip
