version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - pwd
      - zip -r $CODEBUILD_SRC_DIR/artifact/lambda-package.zip .

artifacts:
  files:
    - lambda-package.zip
