version: 0.2

phases:
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - pwd
      - ls
      - zip -r lambda-package.zip .
  post_build:
    commands:
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda-package.zip

artifacts:
  files:
    - lambda-package.zip
