version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - zip -r ../lambda-package.zip .
      - cd ..

artifacts:
  files:
    - lambda-package.zip
