version: 0.2

phases:
  install:
    runtime-versions:
      python: $LAMBDA_PY_RUNTIME
    commands:
      - echo "Login su ECR"
      - echo "ECR repository - $ECR_REPOSITORY"
      - echo "Region - $AWS_REGION"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

  build:
    commands:
      - echo "Costruzione immagine Docker"
      - docker build -t my-lambda-image:$ENV .
      - docker tag my-lambda-image:$ENV $ECR_REPOSITORY:$ENV

  post_build:
    commands:
      - echo "Push immagine su ECR"
      - docker push $ECR_REPOSITORY:$ENV