version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - pwd
      - ls
      - zip -r lambda-package.zip .
  post_build:
    commands:
      - aws lambda update-function-code --function-name simple_lambda --zip-file fileb://lambda-package.zip

artifacts:
  files:
    - lambda-package.zip
